version: '3.8'

services:
  
  api:
    build: .
    ports:
      - "8000:8000"
    
    volumes:
      - ./app:/app
    
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017

  
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: